export const mockVideos = [
    {
        id: '1',
        avatar: '',
        fullname: 'Archi Jonatanek',
        list_number: '1',
        like_count: '0',
        // uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    },
    {
        id: '2',
        avatar: '',
        fullname: 'Ola Vietin',
        list_number: '2',
        like_count: '0',
        uri: 'https://www.w3schools.com/html/mov_bbb.mp4',
    },
    {
        id: '3',
        avatar: '',
        fullname: 'Jeni Jeni',
        list_number: '3',
        like_count: '0',
        uri: 'https://www.w3schools.com/html/movie.mp4',
    },
    {
        id: '4',
        avatar: '',
        fullname: 'Alex Gold',
        list_number: '4',
        like_count: '0',
        uri: 'https://www.w3schools.com/html/mov_bbb.mp4',
    },
    {
        id: '5',
        avatar: '',
        fullname: 'Ahar Lovik',
        list_number: '5',
        like_count: '0',
        uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    },
    {
        id: '6',
        avatar: '',
        fullname: 'Archi Jonatan',
        list_number: '1',
        like_count: '0',
        uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    },
    {
        id: '7',
        avatar: '',
        fullname: 'Ola Vietin',
        list_number: '2',
        like_count: '0',
        uri: 'https://www.w3schools.com/html/mov_bbb.mp4',
    },
    {
        id: '8',
        avatar: '',
        fullname: 'Jeni Jeni',
        list_number: '3',
        like_count: '0',
        uri: 'https://www.w3schools.com/html/movie.mp4',
    },
    {
        id: '9',
        avatar: '',
        fullname: 'Alex Gold',
        list_number: '4',
        like_count: '0',
        uri: 'https://www.w3schools.com/html/mov_bbb.mp4',
    },
    {
        id: '10',
        avatar: '',
        fullname: 'Ahar Lovik',
        list_number: '5',
        like_count: '0',
        uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    },
    {
        id: '11',
        avatar: '',
        fullname: 'Archi Jonatan',
        list_number: '1',
        like_count: '0',
        uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    },
    {
        id: '12',
        avatar: '',
        fullname: 'Ola Vietin',
        list_number: '2',
        like_count: '0',
        uri: 'https://www.w3schools.com/html/mov_bbb.mp4',
    },
    {
        id: '13',
        avatar: '',
        fullname: 'Jeni Jeni',
        list_number: '3',
        like_count: '0',
        uri: 'https://www.w3schools.com/html/movie.mp4',
    },
    {
        id: '14',
        avatar: '',
        fullname: 'Alex Gold',
        list_number: '4',
        like_count: '0',
        uri: 'https://www.w3schools.com/html/mov_bbb.mp4',
    },
    {
        id: '15',
        avatar: '',
        fullname: 'Ahar Lovik',
        list_number: '5',
        like_count: '0',
        uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    },
    {
        id: '16',
        avatar: '',
        fullname: 'Alex Gold',
        list_number: '4',
        like_count: '0',
        uri: 'https://www.w3schools.com/html/mov_bbb.mp4',
    },
    {
        id: '17',
        avatar: '',
        fullname: 'Ahar Lovik',
        list_number: '5',
        like_count: '0',
        uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    },
    {
        id: '18',
        avatar: '',
        fullname: 'Archi Jonatan',
        list_number: '1',
        like_count: '0',
        uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    },
    {
        id: '19',
        avatar: '',
        fullname: 'Ola Vietin',
        list_number: '2',
        like_count: '0',
        uri: 'https://vjs.zencdn.net/v/oceans.mp4',
    },
    {
        id: '20',
        avatar: '',
        fullname: 'Jeni Jeni',
        list_number: '3',
        like_count: '0',
        uri: 'https://www.w3schools.com/html/movie.mp4',
    },
    {
        id: '21',
        avatar: '',
        fullname: 'Alex Gold',
        list_number: '4',
        like_count: '0',
        uri: 'https://www.w3schools.com/html/mov_bbb.mp4',
    },
    {
        id: '22',
        avatar: '',
        fullname: 'Ahar Lovik',
        list_number: '5',
        like_count: '0',
        uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    },
];
